### PR TITLE
Display Hotsname

### PR DESCRIPTION
**Pull request by R3DDY97**
Added code which displays hostnames besides vendors 
as it is raised as isuse by here 
[need hostnames if there are same vendor ](https://github.com/k4m4/kickthemout/issues/105)

### CODE REVIEW

**Comment by k4m4** [comment]
Hi there @R3DDY97. On my first run I got an `Unknown host` error:
```
kickONEOff selected...
Online IPs:Traceback (most recent call last):  File "kickthemout.py", line 489, in <module>    main()
  File "kickthemout.py", line 461, in main
    kickoneoff()
  File "kickthemout.py", line 166, in kickoneoff
    hostname = socket.gethostbyaddr(onlineIPs[i])[0]
socket.herror: [Errno 1] Unknown host
```
I'm looking into socket's docs to see whether this method is effective and applicable for all devices. Thanks!

**Comment by R3DDY97** [comment]
@k4m4 

i tried with 

utils.socket.gethostbyaddr(IP)

it worked 

utils method form scapy 

i have added now utils method before scoket now

try using utils.socket.gethostbyaddr(IP)
and kindly 
let me know 
whether it worked on not 
screenshot from 2017-11-21 13-45-31

**Comment by k4m4** [comment]
Hi there @R3DDY97. Thank you for your contribution and apologies for the (very) late response. Could you please resolve conflicts with master? Thanks again!

**Comment by R3DDY97** [comment]
hi
@k4m4 

i have removed conflicts and made new PR 
Thanks !

**Pull request closed without merging**
