### PR TITLE
Fix ascii art

### PR DESCRIPTION
**Pull request by tobozo**
was probably damaged by the tab settings in some editor

### CODE REVIEW

**Comment by k4m4** [comment]
Hi there @tobozo; thank you for your contribution. The spaces that you removed turn out to be part of the 'design'. :P

**Comment by tobozo** [comment]
oh there's some whitespace coding in there?

**Comment by k4m4** [comment]
Yep, it's how the [ascii art generator formatted it](http://patorjk.com/software/taag/#p=display&f=The%20Edge&t=KickThemOut).

**Comment by tobozo** [comment]
oops so I'm the one damaging things here :[

**Comment by k4m4** [comment]
No worries, you're not damaging anything. Thank you for your contribution!

**Pull request closed without merging**
