### PR TITLE
Create cbuild.sh

### PR DESCRIPTION
**Pull request by the57200**
The cbuild.sh file a bash script for create an executable of kickthemout with cython

### CODE REVIEW

**Comment by the57200** [comment]
You can accept my pull request.

**Comment by k4m4** [comment]
Hi there. Thank you for your contribution.
@xdavidhu and I believe that a cbuild bash file is not required by KickThemOut.
Thanks!

**Comment by the57200** [comment]
Pity

**Comment by the57200** [comment]
Why you don't want to have a script for create an executable ?

**Comment by k4m4** [comment]
We believe that it doesn't add any advantages to the usability of our project.
However, we are looking forward to other ideas/contributions from you. Thank you!

**Pull request closed without merging**
