### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by noraj1337**
Add a note for users that have `python3` as default python. Ex: Archlinux users.

### CODE REVIEW

**Comment by AmauryOrtega** [comment]
This should be on the README

**Comment by noraj1337** [comment]
@k4m4 : When people take from their free time to work on your project to make a PR, you should, at least, tell them why you wontfix and close the PR. This is called respect.

I made a PR to help users, that just add a note on the README. This is helpful and cost nothing for you. So why don't accept it?

**Comment by k4m4** [comment]
Sorry, I thought I had spoken with you about this PR. Of course, your contribution is much appreciated and respected by us. Hadn't you created an issue in which we discussed about this?

**Comment by noraj1337** [comment]
@k4m4 Sorry I forgot about that. https://github.com/k4m4/kickthemout/issues/28

But your conclusion was:

> We might alter it to `pip2`.

Then you closed the issue. So I wish you were going to change the README to `pip2` or accept the PR to add a note. But you did none and close the PR without comment.

**Comment by k4m4** [comment]
I apologize for my inappropriate actions. I always value contributors' suggestions and the effort and time you put into your contributions. We are still thinking about altering `pip` to `pip2`; however, we haven't come across a lot of issues in regards to this. Thanks again! @noraj1337

**Pull request closed without merging**
