### PR TITLE
Added OS X Installation Guide

### PR DESCRIPTION
**Pull request by SentinelWarren**

### CODE REVIEW

**Comment by k4m4** [comment]
Thank you for your contribution! We will take your changes into account.

**Comment by SentinelWarren** [comment]
hey,why did you close my contribution sir and used it for your self?

**Comment by k4m4** [comment]
Hi @SentinelWarren. We wanted to make some changes, and we didn't want to create a new file. Thank you for your aid.

**Comment by SentinelWarren** [comment]
Ok, no problem sir!

**Comment by k4m4** [comment]
By the way, I believe that pypcap is not required on mac in all cases. @SentinelWarren

**Comment by SentinelWarren** [comment]
its very much needed,
 `   s,us = h.getts()
AttributeError: 'NoneType' object has no attribute 'gets'`

That is the error you get when its not installed

**Comment by k4m4** [comment]
I haven't installed it on my mac, and everything runs smoothly.

**Comment by SentinelWarren** [comment]
maybe you have it already, try to `pip uninstall pypcap` it the try the script again
 
Here its the screenshot of the error 
screen shot 2017-01-15 at 1 34 44 pm

**Comment by SentinelWarren** [comment]
it seems some how `scapy` needs `pypcap` to do its job.

**Comment by k4m4** [comment]
Nope. I don't have pypcap, and everything works great mate.

**Comment by k4m4** [comment]
```
~ ❯❯❯ pip uninstall pypcap
Cannot uninstall requirement pypcap, not installed
```

**Comment by SentinelWarren** [comment]
that is strange,,let me keep digging to see what might be the reasons of this differences!

**Comment by k4m4** [comment]
Sure thing. Which Mac OS are you running? Sierra?

**Comment by SentinelWarren** [comment]
yes, sierra

I figured out something already,there should be an issue with my `pcapy`(0.10.10) of which `pypcap` solves the issue!, so i just uninstalled `pcapy`.

**Comment by k4m4** [comment]
Cool. In conclusion, `pypcap` is not required in most cases.

**Comment by SentinelWarren** [comment]
you know `pcapy` and `pypcap` it the same module with different formula/repo. so i figured out on mac sierra `pypcap` works well with scary instead of `pcapy` , So final conclusion is `pypcap` is need  on sierra.

**Comment by k4m4** [comment]
Yes, that's only if `pcap` doesn't work.

**Pull request closed without merging**
